# Generated by Django 2.2.3 on 2019-08-21 01:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=50, verbose_name='Ürün İsmi')),
                ('product_content', ckeditor.fields.RichTextField(verbose_name='Ürün Açıklaması')),
                ('product_created_date', models.DateTimeField(auto_now_add=True, verbose_name='İlan Oluşturulma Tarihi')),
                ('product_slug', models.SlugField(default='defaultVal', unique=True)),
                ('product_meta_description', models.CharField(default='default meta acıklaması', max_length=250, verbose_name='Makale Meta Açıklaması')),
                ('product_price', models.CharField(choices=[('TL', 'TL'), ('$', '$'), ('€', '€')], default='fiyat', max_length=50, verbose_name='Ürün Fiyatı')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ürün Resmi')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ('-product_created_date',),
            },
        ),
    ]
