# Generated by Django 2.2.3 on 2019-08-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price_unit',
            field=models.CharField(choices=[('TL', 'TL'), ('$', '$'), ('€', '€')], default='fbirim', max_length=50, verbose_name='Ürün Fiyatı Birimi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(max_length=50, verbose_name='Ürün Fiyatı'),
        ),
    ]
