# Generated by Django 2.2.3 on 2019-08-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190821_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iletisim_isim', models.CharField(max_length=100, null=True, verbose_name='isim')),
                ('iletisim_mail', models.CharField(max_length=100, verbose_name='email')),
                ('iletisim_telefon', models.CharField(max_length=100, verbose_name='telefon')),
                ('iletisim_mesaj', models.TextField(verbose_name='mesaj')),
                ('iletisim_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='İletişim Formu Gönderilme Tarihi')),
            ],
            options={
                'verbose_name': 'İletişim Talebi',
                'verbose_name_plural': 'İletişim Talepleri',
                'ordering': ('-iletisim_tarihi',),
            },
        ),
    ]
